[issue #7] ResultSetMapper implementation
bobocode-blyznytsia/bibernate pull request #27
Opened 2023-04-03 23:07 UTC by marynamelnichuk

2023-04-04 12:46 UTC, olehhaliak requested changes

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/exception/MalformedEntityException.java
> + * Exception class for errors that occurs when an entity is not properly formed
'occur' in this sentence refers to 'errors', plural. So there should be no 's' at the end

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/exception/PersistenceException.java
> + * Exception for errors that occurs during persistence operations within
errors - plural - no 's'

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/mapper/ResultSetMapper.java
> + * The interface consists methods for mapping instance of {@link ResultSet} to entity.
consist of / contains

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/DateUtil.java
> +      return true;
please, use true/false combination, or make this method void

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/RelationsUtil.java
> +    if (joinColumnName == null || joinColumnName.isEmpty()) {
what about the scenario when joinColumnName is blank?

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/RelationsUtil.java
> +    if (mappedBy == null || mappedBy.isEmpty()) {
blank?

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/RelationsUtil.java
> +            "Field %s that was specified in mapped by in parent class doesn't exist in class %s",
Optional: you can use `"str".formatted() here` instead of `String. format()`. Not critical by any means, just subjectively looks a bit cleanerd

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/SqlUtil.java
> -    var searchColumnName = resolveFieldColumnName(key);
Please note that `resolveFieldColumnName()` not just uses a field name, but tries to resolve the column by annotation `@Column`, and if such annotation is not present - it converts the field name to snake_case.
Consider following examples:
``` java
  @Entity
  private class EntityWithCustomId{
    @Id
    @Column(name = "my_id")
    Long id;
  }

  @Entity
  private class EntityWithLongId{
    @Id
    Long longIdColumn;
  }
  @Test
  void test() {
     entityPersister.findById(EntityWithLongId.class,1L);
     // expected query to be executed : SELECT * FROM entity_with_long_id WHERE long_id_column = ?
     // actual query to be executed   : SELECT * FROM entity_with_long_id WHERE longIdColumn = ?
     entityPersister.findById(EntityWithCustomId.class,1L);
     // expected : SELECT * FROM entity_with_custom_id WHERE my_id = ?
     // actual   : SELECT * FROM entity_with_custom_id WHERE id = ?
  }
```

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/persister/EntityPersisterImpl.java
> +    return findOneBy(entityType, EntityUtil.resolveEntityIdField(entityType).getName(), id);
Take a look at the `SqlUtil` comment

2023-04-04 12:46 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/mapper/ResultSetMappedEntitiesContext.java
It's a bit unclear to me what's the purpose of this class. Is it something like ResultSet-local PersistenceContext?

2023-04-04 13:58 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/SqlUtil.java
> -    var searchColumnName = resolveFieldColumnName(key);
Thanks, I understand this. But for querying relational fields I need to specify database column name that can be specified in "joinColumnName" property. For example:

`
Entity1:
@Entity
@Table(name = "persons")
public class PersonWithOneToOne {

  @Id
  private Integer id;

  private String firstName;

  private String lastName;

  private LocalDate birthday;

  @OneToOne(mappedBy = "person")
  private Address address;

}

Enity2:

@Entity
@Table(name = "addresses")
public class Address {

  @Id
  private Long id;

  private String city;

  private String street;

  @OneToOne(joinColumnName = "person_id")
  private PersonWithOneToOne person;

}
`
**_To find person address I need to search by person_id in table addresses not by person field._**

2023-04-04 14:04 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/exception/MalformedEntityException.java
> + * Exception class for errors that occurs when an entity is not properly formed
fixed

2023-04-04 14:05 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/exception/PersistenceException.java
> + * Exception for errors that occurs during persistence operations within
fixed

2023-04-04 14:05 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/mapper/ResultSetMapper.java
> + * The interface consists methods for mapping instance of {@link ResultSet} to entity.
fixed

2023-04-04 14:05 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/DateUtil.java
> +      return true;
fixed

2023-04-04 14:05 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/RelationsUtil.java
> +    if (joinColumnName == null || joinColumnName.isEmpty()) {
fixed

2023-04-04 14:05 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/RelationsUtil.java
> +    if (mappedBy == null || mappedBy.isEmpty()) {
fixed

2023-04-04 14:05 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/RelationsUtil.java
> +            "Field %s that was specified in mapped by in parent class doesn't exist in class %s",
fixed

2023-04-04 14:11 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/persister/EntityPersisterImpl.java
> +    return findOneBy(entityType, EntityUtil.resolveEntityIdField(entityType).getName(), id);
Let's use resolveFieldColumnName() to get the proper id column name here

2023-04-04 14:12 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/mapper/ResultSetMappedEntitiesContext.java
`ResultSetMappedEntitiesContext` is used to save partially mapped entities, this only happens when we have relationships. For example, I have `User` class and it has `List<Note> notes` field, before querying the notes I put `User` instance in the cache, so that in the `Note` class, which has a `User user` field, it can be retrieved from the cache and not queried from the database. Because if I don't do this, `user` will be queried from the database again, and then `notes`, and after that, we will have StackOverflowException thrown.

2023-04-04 14:20 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/SqlUtil.java
> -    var searchColumnName = resolveFieldColumnName(key);
Understood, then I`m fine with using an actual column name as a key in findOneBy & findAllBy.
Just update Javadoc to make it clear, please.

2023-04-04 16:14 UTC, MykolaHarasym approved these changes

2023-04-04 21:04 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/persister/EntityPersisterImpl.java
> +    return findOneBy(entityType, EntityUtil.resolveEntityIdField(entityType).getName(), id);
Fixed: updated EntityPersister Java docs.

2023-04-04 21:04 UTC, marynamelnichuk commented on src/main/java/com/bobocode/blyznytsia/bibernate/util/SqlUtil.java
> -    var searchColumnName = resolveFieldColumnName(key);
Fixed: updated EntityPersister Java docs.

2023-04-05 06:13 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/persister/EntityPersisterImpl.java
> +    return findOneBy(entityType, EntityUtil.resolveEntityIdField(entityType).getName(), id);
`resolveEntityIdField(entityType)` returns `Field`

2023-04-05 06:24 UTC, olehhaliak approved these changes
Impressive!

2023-04-05 06:36 UTC, merged