[Issue- #22] Abstraction to work with Entity:  Native query API
bobocode-blyznytsia/bibernate pull request #32
Opened 2023-04-05 13:28 UTC by olehhaliak

This is the first PR related to issue #22 Abstraction to work with an entity.
Query API allows users to create custom native queries, and will be used as a base to build repository abstraction later on

2023-04-05 14:00 UTC, vitshch requested changes

2023-04-05 14:00 UTC, vitshch commented on src/main/java/com/bobocode/blyznytsia/bibernate/exception/MissingParamsException.java
> + * Exception thrown during {@link   Query} execution in case when one or more parameters
Some extra spaces between @link and Query

2023-04-05 14:00 UTC, vitshch commented on src/main/java/com/bobocode/blyznytsia/bibernate/query/Query.java
> +}
Add newline at the end of the file

2023-04-05 14:00 UTC, vitshch commented on src/test/java/com/bobocode/blyznytsia/bibernate/query/TypedQueryTest.java
> +}
Add newline at the end

2023-04-05 20:13 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/query/Query.java
> +}
fixed

2023-04-05 20:14 UTC, olehhaliak commented on src/test/java/com/bobocode/blyznytsia/bibernate/query/TypedQueryTest.java
> +}
fixed

2023-04-05 20:14 UTC, olehhaliak commented on src/main/java/com/bobocode/blyznytsia/bibernate/exception/MissingParamsException.java
> + * Exception thrown during {@link   Query} execution in case when one or more parameters
fixed

2023-04-05 20:14 UTC, olehhaliak commented on src/test/java/com/bobocode/blyznytsia/bibernate/query/TypedQueryTest.java
> +}
fixed

2023-04-06 06:35 UTC, marynamelnichuk approved these changes
I hope unit tests will be in the next PR.

2023-04-06 06:39 UTC, vitshch approved these changes

2023-04-06 12:18 UTC, merged